### ISSUE TITLE
予約QRの仕様変更

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/manage-app#182]
afes-website/docs#287
`[rsv_id]:[date(MMDD)]:[time1(HHMM)]:[time2(HHMM)]:[hash(2)]` の形式を取る
例：`R-11111-11111:1115:1000:1200:AA`

@su8ru @ibuki2003 これでよいですか

**Comment by ibuki2003** [comment]
決まったこと: 署名をECDSAでセミコロン区切りの後半にbase64で埋め込む
